export const MOCK_CLIENTS = [
  { id: 1, name: "Acme Corp", status: "Active" },
  { id: 2, name: "Global Tech", status: "Active" },
  { id: 3, name: "Nebula Systems", status: "Active" },
  { id: 4, name: "Starlight Inc", status: "Inactive" },
];

export const MOCK_TEAM = [
  {
    id: 1,
    name: "Kazi Nowshad Abir",
    role: "Managing Director",
    email: "nowshad@vivagodigital.com",
    phone: "+880 1711 000000",
    status: "Active",
    expertise: ["Full-Stack", "Frontend Focused", "PHP", "MySQL", "HTML/CSS/JS"],
    projects: ["E-commerce Redesign", "LodgeOS Integration"],
    image: "/uploads/profiles/avatar.png",
  },
  {
    id: 2,
    name: "Imtiaz",
    role: "CEO",
    email: "imtiaz@vivagodigital.com",
    phone: "+880 1811 000000",
    status: "Active",
    expertise: ["Full Stack", "Backend Focused", "System Architecture", "Security"],
    projects: ["E-commerce Redesign", "LodgeOS Integration"],
    image: null,
  },
];

export const MOCK_PROJECTS = [
  {
    id: 1,
    name: "E-commerce Redesign",
    clientId: 1,
    clientName: "Acme Corp",
    status: "In Progress",
    startDate: "2024-03-01",
    estimatedDeadline: "2024-05-15",
    valuation: 250000,
    companyCost: 45000,
    temporaryCost: 12000,
    client: { name: "Acme Corp" },
    createdAt: new Date("2024-03-01"),
    team: [
      { name: "Kazi Nowshad Abir", role: "Managing Director" },
      { name: "Imtiaz", role: "CEO" },
    ],
  },
  {
    id: 2,
    name: "LodgeOS Integration",
    clientId: 2,
    clientName: "Global Tech",
    status: "Review",
    startDate: "2024-02-15",
    estimatedDeadline: "2024-04-20",
    valuation: 450000,
    companyCost: 85000,
    temporaryCost: 25000,
    client: { name: "Global Tech" },
    createdAt: new Date("2024-02-15"),
    team: [
      { name: "Nowshad Abir", role: "Frontend Lead" },
      { name: "Imtiaz", role: "CEO" },
    ],
  },
  {
    id: 3,
    name: "Mobile App Development",
    clientId: 3,
    clientName: "Nebula Systems",
    status: "Planning",
    startDate: "2024-04-01",
    estimatedDeadline: "2024-07-30",
    valuation: 600000,
    companyCost: 120000,
    temporaryCost: 0,
    client: { name: "Nebula Systems" },
    createdAt: new Date("2024-04-01"),
    team: [
      { name: "Abir", role: "Art Director" },
    ],
  },
  {
    id: 4,
    name: "Brand Identity",
    clientId: 1,
    clientName: "Acme Corp",
    status: "Completed",
    startDate: "2024-01-10",
    estimatedDeadline: "2024-02-28",
    valuation: 120000,
    companyCost: 20000,
    temporaryCost: 5000,
    client: { name: "Acme Corp" },
    createdAt: new Date("2024-01-10"),
    team: [
      { name: "Nowshad Abir", role: "Creative Lead" },
    ],
  },
];

export const MOCK_REMINDERS = [
  {
    id: 1,
    title: "Client Meeting: Acme Corp",
    note: "Discuss progress on e-commerce redesign and next milestones.",
    dueDate: "2024-04-12",
    dueTime: "10:00 AM",
    priority: "High",
    status: "Pending",
  },
  {
    id: 2,
    title: "Project Handover: Brand Identity",
    note: "Finalize all assets and send to client.",
    dueDate: "2024-04-15",
    dueTime: "04:00 PM",
    priority: "Medium",
    status: "Pending",
  },
  {
    id: 3,
    title: "Review Financial Health",
    note: "Month-end financial review and reporting.",
    dueDate: "2024-04-30",
    dueTime: "11:00 AM",
    priority: "Low",
    status: "Pending",
  },
];

export const MOCK_DUE_RECORDS = [
  {
    id: 1,
    clientId: 1,
    clientName: "Acme Corp",
    projectId: 1,
    projectName: "E-commerce Redesign",
    dueDate: "2024-05-15",
    amount: 100000,
    status: "Upcoming",
    note: "Final payment due",
  },
  {
    id: 2,
    clientId: 2,
    clientName: "Global Tech",
    projectId: 2,
    projectName: "LodgeOS Integration",
    dueDate: "2024-04-05",
    amount: 50000,
    status: "Overdue",
    note: "Phase 2 payment pending",
  },
  {
    id: 3,
    clientId: 3,
    clientName: "Nebula Systems",
    projectId: 3,
    projectName: "Mobile App Development",
    dueDate: "2024-04-10",
    amount: 150000,
    status: "Due Today",
    note: "Advance for mobile development",
  },
];

export const MOCK_PAYMENTS = [
  {
    id: 1,
    date: "2024-03-25",
    party: "Acme Corp",
    projectId: 1,
    projectName: "E-commerce Redesign",
    purpose: "Advance Payment",
    acknowledgement: "Advance Payment",
    method: "Bank Transfer",
    amount: 150000,
    flow: "Received",
    costResponsibility: null,
    status: "Completed",
    note: "TRX#552145",
  },
  {
    id: 2,
    date: "2024-03-20",
    party: "H-One Softwares",
    projectId: 2,
    projectName: "LodgeOS Integration",
    purpose: "Server Setup Cost",
    acknowledgement: null,
    method: "Mobile Banking",
    amount: 45000,
    flow: "Given",
    costResponsibility: "Company Expense",
    status: "Completed",
    note: "BKASH#991122",
  },
  {
    id: 3,
    date: "2024-04-01",
    party: "Digital Ocean",
    projectId: 1,
    projectName: "E-commerce Redesign",
    purpose: "Hosting Credits",
    acknowledgement: null,
    method: "Card",
    amount: 12000,
    flow: "Given",
    costResponsibility: "Client Reimbursable",
    reimbursementClient: "Acme Corp",
    status: "Completed",
    note: "Invoice #DO-2233",
  },
  {
    id: 4,
    date: "2024-04-02",
    party: "Starlight Inc",
    projectId: null,
    projectName: null,
    purpose: "Domain Purchase",
    acknowledgement: "Advance Payment",
    method: "Bank Transfer",
    amount: 25000,
    flow: "Received",
    costResponsibility: null,
    status: "Pending",
    note: "Waiting for confirmation",
  },
  {
    id: 5,
    date: "2024-04-05",
    party: "Office Rent",
    projectId: null,
    projectName: null,
    purpose: "Rent April 2024",
    acknowledgement: null,
    method: "Cash",
    amount: 35000,
    flow: "Given",
    costResponsibility: "Company Expense",
    status: "Completed",
    note: "Cash payment",
  },
];

export const MOCK_PROFIT_LOSS = [
  {
    id: 1,
    clientId: 1,
    clientName: "Acme Corp",
    projectId: 1,
    projectName: "E-commerce Redesign",
    revenue: 250000,
    companyCost: 65000,
    temporaryCost: 15000,
    note: "High margin project",
  },
  {
    id: 2,
    clientId: 2,
    clientName: "Global Tech",
    projectId: 2,
    projectName: "LodgeOS Integration",
    revenue: 450000,
    companyCost: 120000,
    temporaryCost: 35000,
    note: "Integration phase complete",
  },
];

export const MOCK_FILES = [
  {
    id: 1,
    projectId: 1,
    projectName: "E-commerce Redesign",
    fileName: "home-page.tsx",
    language: "TypeScript",
    sizeKb: 12,
    storagePath: "/src/app/home-page.tsx",
    fileDate: "2024-03-25",
    status: "Active",
    note: "Main entry point",
  },
  {
    id: 2,
    projectId: 2,
    projectName: "LodgeOS Integration",
    fileName: "api-types.ts",
    language: "TypeScript",
    sizeKb: 8,
    storagePath: "/src/types/api.ts",
    fileDate: "2024-04-01",
    status: "Draft",
    note: "Initial types",
  },
  {
    id: 3,
    projectId: 1,
    projectName: "E-commerce Redesign",
    fileName: "service-agreement-v1.pdf",
    language: "PDF",
    sizeKb: 245,
    storagePath: "/uploads/agreements/service-agreement-v1.pdf",
    fileDate: "2024-03-01",
    status: "Archived",
    note: "Initial agreement",
  },
  {
    id: 4,
    projectId: 1,
    projectName: "E-commerce Redesign",
    fileName: "service-agreement-v2-final.pdf",
    language: "PDF",
    sizeKb: 260,
    storagePath: "/uploads/agreements/service-agreement-v2-final.pdf",
    fileDate: "2024-03-15",
    status: "Active",
    note: "Updated agreement with new terms",
  },
  {
    id: 5,
    projectId: 2,
    projectName: "LodgeOS Integration",
    fileName: "master-agreement.docx",
    language: "Word",
    sizeKb: 120,
    storagePath: "/uploads/agreements/master-agreement.docx",
    fileDate: "2024-02-15",
    status: "Active",
    note: "Project master agreement",
  },
];

export const MOCK_CREDENTIALS = [
  {
    id: 1,
    projectId: 1,
    projectName: "E-commerce Redesign",
    category: "Hosting",
    service: "AWS",
    username: "admin_user",
    password: "password123",
    endpoint: "https://console.aws.amazon.com",
    reviewDate: "2024-05-01",
    status: "Active",
    note: "Primary hosting",
  },
  {
    id: 2,
    projectId: 2,
    projectName: "LodgeOS Integration",
    category: "Database",
    service: "Supabase",
    username: "db_admin",
    password: "db_password_456",
    endpoint: "https://supabase.com",
    reviewDate: "2024-06-15",
    status: "Active",
    note: "Postgres DB",
  },
];

export const MOCK_ASSETS = {
  credentials: MOCK_CREDENTIALS,
  files: MOCK_FILES,
};
