CREATE TABLE IF NOT EXISTS User (
  id VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  position VARCHAR(191) NULL,
  username VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL,
  password VARCHAR(191) NOT NULL,
  role ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
  image VARCHAR(191) NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY User_username_key (username),
  UNIQUE KEY User_email_key (email)
);

CREATE TABLE IF NOT EXISTS auth_otp (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(191) NOT NULL,
  purpose VARCHAR(191) NOT NULL,
  codeHash VARCHAR(191) NOT NULL,
  payload LONGTEXT NULL,
  expiresAt DATETIME NOT NULL,
  verifiedAt DATETIME NULL,
  attempts INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NULL,
  PRIMARY KEY (id)
);